import Head from "next/head";
import { Inter } from "@next/font/google";
import ProjectContainer from "../components/projects/projectContainer";
import AboutMe from "../components/aboutme";
import clientPromise from "../lib/mongodb";
import { Project } from "../components/types/project";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ Projects }: { Projects: Project[] }) {
  return (
    <>
      <Head>
        <title>Ajay Ganesh!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center content-center">
        <div className="w-full h-full md:w-2/3 p-8">
        <AboutMe />
        <div className="divider"></div>
        <ProjectContainer Projects={Projects} />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const client = await clientPromise;
    const projects = await client
      .db("Portfolio")
      .collection("Projects")
      .find({})
      .project({
        name: 1,
        tags: 1,
        link: 1,
        img: 1,
        visit: 1,
        _id: 0,
      })
      .toArray();
    return {
      props: { Projects: projects },
      revalidate: 60,
    };
  } catch (e) {
    console.error(e);
    return {
      props: { Projects: [] },
    };
  }
}
